[package]
name = "icarus_auth"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.3" }
serde = { version = "1.0.218", features = ["derive"] }
serde_json = { version = "1.0.139" }
tokio = { version = "1.44.1", features = ["rt-multi-thread"] }
tracing-subscriber = { version = "0.3.19" }
tower = { version = "0.5.2" }
hyper = { version = "1.6.0" }
sqlx = { version = "0.8.3", features = ["postgres", "runtime-tokio-native-tls"] }
dotenv = { version = "0.15" }
icarus_models = { git = "ssh://git@git.kundeng.us/phoenix/icarus_models.git", tag = "v0.2.0" }

[dev-dependencies]
http-body-util = "0.1.3"
reqwest = { version = "0.12.5", features = ["json"] } # For making HTTP requests in tests
once_cell = "1.19" # Useful for lazy initialization in tests/app setup
